#!/bin/bash

# Script to set up Task Planner reminders using Windows Task Scheduler
# This script creates a Windows scheduled task that runs every minute for testing

echo "Setting up Task Planner scheduled task for Windows..."

# Get the absolute Windows path to the directory containing this script
SCRIPT_DIR_WSL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Convert WSL path to Windows path properly
SCRIPT_DIR_WIN=$(echo "$SCRIPT_DIR_WSL" | sed 's|^/mnt/\([a-z]\)|\U\1:|')

# Construct paths
BAT_FILE_PATH_WIN="$SCRIPT_DIR_WIN\\run_cron.bat"

echo "Script directory (Windows): $SCRIPT_DIR_WIN"

# Check if cron.php exists
if [ ! -f "$SCRIPT_DIR_WSL/cron.php" ]; then
    echo "ERROR: cron.php not found at $SCRIPT_DIR_WSL/cron.php"
    exit 1
fi

# Create a batch file to run the PHP script
echo "Creating batch file: $BAT_FILE_PATH_WIN"
cat > "$SCRIPT_DIR_WSL/run_cron.bat" << 'EOF'
@echo off
REM Batch file to run Task Planner CRON job
REM This file is auto-generated by setup_cron.sh

cd /d "%~dp0"

REM Try different PHP locations
if exist "C:\xampp\php\php.exe" (
    "C:\xampp\php\php.exe" cron.php
    goto :end
)

if exist "C:\php\php.exe" (
    "C:\php\php.exe" cron.php
    goto :end
)

if exist "C:\wamp64\bin\php\php8.2.13\php.exe" (
    "C:\wamp64\bin\php\php8.2.13\php.exe" cron.php
    goto :end
)

if exist "C:\laragon\bin\php\php82\php.exe" (
    "C:\laragon\bin\php\php82\php.exe" cron.php
    goto :end
)

REM Try to use php from PATH
php.exe cron.php 2>nul
if %errorlevel% neq 0 (
    echo ERROR: PHP not found. Please ensure PHP is installed and in your PATH.
    echo Or update this batch file with the correct PHP path.
    echo Attempted to run: %~dp0cron.php
    pause
)

:end
EOF

if [ $? -eq 0 ]; then
    echo "Batch file created successfully."
else
    echo "ERROR: Failed to create batch file."
    exit 1
fi

# Create the Windows scheduled task
TASK_NAME="TaskPlannerReminder"

echo "Creating Windows scheduled task: $TASK_NAME"
echo "This may require Administrator privileges..."

# Delete existing task if it exists (suppress error output)
cmd.exe /c "schtasks /delete /tn \"$TASK_NAME\" /f >nul 2>&1"

# Create new scheduled task (runs every minute for testing)
SCHTASKS_CMD="schtasks /create /tn \"$TASK_NAME\" /tr \"\\\"$BAT_FILE_PATH_WIN\\\"\" /sc minute /mo 1 /f /rl highest"

echo "Executing: $SCHTASKS_CMD"
cmd.exe /c "$SCHTASKS_CMD"

RESULT=$?
if [ $RESULT -eq 0 ]; then
    echo ""
    echo "✅ Scheduled task created successfully!"
    echo "Task Name: $TASK_NAME"
    echo "Schedule: Every 1 minute (for testing)"
    echo "Command: $BAT_FILE_PATH_WIN"
    echo ""
    echo "The task will use your existing Windows sendmail configuration."
    echo ""
    echo "To verify the task was created, run:"
    echo "schtasks /query /tn \"$TASK_NAME\""
    echo ""
    echo "To manually test the script, run: $BAT_FILE_PATH_WIN"
else
    echo ""
    echo "❌ ERROR: Failed to create scheduled task (Error code: $RESULT)"
    echo ""
    echo "This usually means:"
    echo "1. You need to run this script as Administrator"
    echo "2. Or Windows Task Scheduler service is not running"
    echo ""
    echo "Try:"
    echo "1. Right-click Command Prompt and 'Run as Administrator'"
    echo "2. Then run this script again"
    echo ""
    echo "You can also manually create the task by running:"
    echo "$SCHTASKS_CMD"
    
    exit 1
fi

echo ""
echo "Setup complete."
echo "The scheduled task is now running every minute using Windows PHP with your sendmail configuration."
